Импорт табличной части в исходящих письмах.
DirectumCompany/rx-util-importdata-net-core pull request #21
Opened 2022-11-03 12:00 UTC by mnocard

Заполнение коллекции на вкладке Адресаты в исходящих письмах.

2022-11-05 09:19 UTC, gureev requested changes

2022-11-05 09:19 UTC, gureev commented on src/ImportData/Constants.cs
> +      public const string OutgoingLettersAddressees = "ИсходящиеПисьмаТабличнаяЧасть";
Лучше бы лист назвать ИсходящиеПисьмаСписокПолучателей, а то не понятно что за табличная часть

2022-11-05 09:19 UTC, gureev commented on src/ImportData/IntegrationServicesClient/Models/IOutgoingLetters.cs
> +        if (!IsManyAddressees)
Какое-то не очевидное колдунство. Зачем тогда вообще этот флаг, если он всегда в true устанавливается? И если он всегда нужен в true, то зачем условие, можно ж просто ему значение установить.

2022-11-05 09:19 UTC, gureev commented on src/ImportData/Entities/EDocs/OutgoingLetterAddressees.cs
> +        var message = string.Format("Не удалось обработать Id документа \"{0}\".", this.Parameters[shift + 0].Trim());
1. Сообщение об ошибке не соответствует самой ошибке. Не удалось ведь распарсить параметр в число, а не обработать документ. И неплохо бы описание исходного исключения пробросить в результат.
2. this.Parameters[shift + 0].Trim() уже вынесено в переменную, лучше переиспользовать ее.

2022-11-05 09:56 UTC, mnocard commented on src/ImportData/IntegrationServicesClient/Models/IOutgoingLetters.cs
> +    public IEmployees ResponsibleForReturnEmployee { get; set; }
Это название параметра в DirectumRX. Его нельзя менять, так как он должен совпадать со значением из DirectumRX.

2022-11-05 09:57 UTC, mnocard commented on src/ImportData/IntegrationServicesClient/Models/IOutgoingLetters.cs
> +    public IEmployees Addressee { get; set; }
Это параметр в DirectumRX в исходящих письмах. Если в исходящем письме один получатель, то он указывается в Addressee, если получателей несколько, то Addressees.

2022-11-05 10:00 UTC, mnocard commented on src/ImportData/IntegrationServicesClient/Models/IOutgoingLetters.cs
> +        if (!IsManyAddressees)
В true его надо устанавливать, только если у письма несколько получателей. Перед установкой в true, проверяем, что ранее свойство не устанавливалось в true, чтобы несколько раз не обращаться к свойству.

2022-11-05 10:07 UTC, mnocard commented on src/ImportData/Entities/EDocs/OutgoingLetterAddressees.cs
> +        var message = string.Format("Не удалось обработать Id документа \"{0}\".", this.Parameters[shift + 0].Trim());
1. В колонке должен быть указан Id документа, поэтому в сообщении об ошибке пишем, что не удалось обработать Id документа.
Все методы, комментарии и сообщения я делал в соответствии с учетом стиля кода всего приложения, чтобы было единообразие.
2. Исправил.

2022-11-05 10:07 UTC, mnocard commented on src/ImportData/Constants.cs
> +      public const string OutgoingLettersAddressees = "ИсходящиеПисьмаТабличнаяЧасть";
Исправил.

2022-11-05 10:07 UTC, mnocard commented on src/ImportData/Entities/EDocs/OutgoingLetterAddressees.cs
> +    public override IEnumerable<Structures.ExceptionsStruct> SaveToRX(Logger logger, bool supplementEntity, string ignoreDuplicates, int shift = 0)
К сожалению, в базовом методе эти параметры не описаны и в других сущностях не используются, поэтому не могу с уверенностью сказать для чего эти параметры. В текущей реализации импорта табличной части они мной не используются.

2022-11-05 10:07 UTC, mnocard commented on src/ImportData/Entities/EDocs/OutgoingLetterAddressees.cs
> +    /// Получить наименование число запрашиваемых параметров.
Исправил

2022-11-05 18:07 UTC, gureev approved these changes

2022-11-05 18:09 UTC, gureev commented on src/ImportData/Entities/EDocs/OutgoingLetterAddressees.cs
> +        var message = string.Format("Не удалось обработать Id документа \"{0}\".", this.Parameters[shift + 0].Trim());
Как вариант, можно было бы написать "не удалось получить". Ну да ладно, без более подробной информации из исключения все равно не сильно понятнее станет.

2022-11-06 07:08 UTC, gureev commented on src/ImportData/IntegrationServicesClient/Models/IOutgoingLetters.cs
> +        if (!IsManyAddressees)
Но ведь для проверки свойства все равно к нему обращаться приходится. Плюс судя по ответу, значение как-то должно зависеть от кол-ва получателей, но кроме проверки значения самого флага ничего не проверяется

2022-11-06 07:13 UTC, gureev reviewed
Сброшу свой голос, т.к. это не мой основной репозиторий

2022-12-04 11:33 UTC, merged