Fix import company 20221109
DirectumCompany/rx-util-importdata-net-core pull request #25
Opened 2022-11-10 06:20 UTC by mnocard

Доработан импорт оргструктуры для 4.4:
- Сотрудники не импортировались, так как в 4.4 появилось свойство NeedNotifyAssignmentsSummary в карточке сотрудника.
- Ранее в IRecipients было добавлено свойство Login, которое вызывало ошибку при импорте подразделений и наших организаций. С учетом наличия данного свойства в IUsers, класс IEmployees наследуется теперь от него, а не от IRecipients.
- Добавлена проверка на дубликаты при импорте сотрудников, персон, подразделений и наших организаций.

Ограничения:
- Из-за добавленного свойства NeedNotifyAssignmentsSummary могут возникать ошибки при импорте сотрудников в версиях DirectumRX 4.3 и ниже.

2022-12-04 11:51 UTC, ardashev-dev requested changes

2022-12-04 11:51 UTC, ardashev-dev commented on src/ImportData/IntegrationServicesClient/Models/IEmployees.cs
> +    public class IEmployees : IUsers
Почему не IRecipients ?

2022-12-04 11:51 UTC, ardashev-dev commented on src/ImportData/IntegrationServicesClient/Models/IRecipients.cs
> -        public ILogins Login { get; set; }
надо обсудить

2022-12-19 11:36 UTC, mnocard commented
Теперь по умолчанию утилита будет пытаться импортировать версию модели сотрудника для Directum RX 4.4 и выше. При неудачной попытке будет использоваться модель для Directum RX 4.3 и ниже.

2023-01-10 07:12 UTC, mnocard commented on src/ImportData/IntegrationServicesClient/Models/IEmployees.cs
> +    public class IEmployees : IUsers
Обсудили голосом: в IUsers и IRecipients дублируются свойства Login, при этом от IRecipients наследуются ещё и организации и подразделения, которые не импортируются при наличии свойства Login. Свойство было убрано из IRecipients, но чтобы IEmployees сохранил свойство Login, наследование было изменено на IUsers

2023-01-10 07:12 UTC, mnocard commented on src/ImportData/IntegrationServicesClient/Models/IRecipients.cs
> -        public ILogins Login { get; set; }
Удалено, так как дублируется в IUsers

2023-01-10 07:28 UTC, ardashev-dev approved these changes

2023-01-10 07:29 UTC, ardashev-dev approved these changes

2023-01-10 07:29 UTC, merged